include: package:flutter_lints/analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_unused_constructor_parameters
    - camel_case_types
    - constant_identifier_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - sort_child_properties_last
    - valid_regexps